### ISSUE TITLE
Weird errors when including @polkadot/api package

### ISSUE THREAD

**Issue by trusch** [MetaMask/snaps#1012]
I'm encountering strange errors when I try to include @polkadot/api into my snap. It compiles fine, but when I actually have code inside which creates an API client the mm-snap eval step gives me the error `[TypeError <Object <Object <[Object: null prototype] {}>>>: window.addEventListener is not a function`

I guess somehow the api client wants to use the window object which is not available in SES mode, but I know that there are snaps which successfully used the polkadot API client (https://github.com/ChainSafe/metamask-snap-polkadot). I used the very same versions but with no success. 

Could someone provide any hints how to get rid of this problem?

**Comment by FrederikBolding** [comment]
Hi! You may have to patch the `@polkadot/api` package to get it working in SES.

A snap cannot access the DOM so `addEventListener` is not usable. You can look through the library code and patch out any usage of this to get it running in SES. Here is a guide: https://docs.metamask.io/guide/snaps-patching-dependencies.html

Let me know if that is of any help!

**Comment by trusch** [comment]
@FrederikBolding thank you, I'll try it out as fast as possible and come back!
