### ISSUE TITLE
Signature insights for signature confirmations SIP

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1024]
SIP for signature insights. Similar to transaction insights, snaps would like to receive the signature payload and decode it for the user. Will use tx insights v2 UI, where the Snap is always called, and in this case the warning is only displayed if it's severity: 1. Use "onSignature" export.

**Comment by lljxx1** [comment]
+1

**Comment by ethereumdegen** [comment]
+1

**Comment by ethereumdegen** [comment]
+1

**Comment by kenhkan** [comment]
From refinement:
- Waiting for confirmations redesign.
- Not high priority from community

**Comment by Montoya** [comment]
Closing and tracking in a separate issue
