### ISSUE TITLE
Link to the environment variables example project in some way

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1072]
This example: https://github.com/onetrickwolf/env-snap-example/tree/main/packages/snap

Adds support for environment variables. It was brought up in this issue: 

https://github.com/MetaMask/snaps-monorepo/issues/679

We do not plan to make this a native feature in the CLI but we should document this example somewhere for anyone else who wants to use it.

**Comment by ziad-saab** [comment]
@Montoya would you be OK to close this ticket in favor of MetaMask/metamask-docs#746?

**Comment by Montoya** [comment]
Yes, closing
