### ISSUE TITLE
Create a Snap simulator

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps#1178]
We have a very rudimentary verification step during build in the Snaps CLI that runs the bundle in the sandbox with stubs for any external communication.

Having a Snap sandbox be runnable as a separate entity, be it in the iFrame execution environment, Node or Snaps CLI would be helpful for debugging purposes.

@naugtur said he would greatly benefit from such a system where he could set-up the env and run a snap (or few for e2e testing) with one command.

**Comment by Montoya** [comment]
Done!
