### ISSUE TITLE
Entropy based on selected address instead of entropy based on 12 words

### ISSUE THREAD

**Issue by immortal-tofu** [MetaMask/snaps#1200]
Hello,
Our goal is to implement a snap that derivate a TFHE key from a seed coming from your selected address. Right now, snap API gives you a BIP32/44 entropy based on your 12 words seed.

So `snap_getBip44Entropy` gives you the same entropy, no matter the selected address. It's impossible to have different derivated keys depending of the selected address.
Worst, if you import a private key, the entropy is still based on the 12 words of your wallet. If you import a private key on wallet A and wallet B, you end with 2 different entropy, so 2 different keys.

Is it planned to give an API to derive a deterministic entropy based on the selected key/address?

**Comment by ritave** [comment]
What is your ask here?

MetaMask uses hierarchical accounts, meaning you can request the extended private key for ethereum using Bip44 with cointype 60 and then use `@metamask/key-tree` to derive all the subaccounts visible in the MetaMask interface. `m/44’/60’/0’/0` is the Account 1, `m/44’/60’/0’/1` is the Account 2, and so on.

**Comment by Montoya** [comment]
It is not possible to tell which address is the currently selected address. I think the best approach would be prompt the user with a dialog of type "prompt" to input their public key and then derive an address based on that.

**Comment by immortal-tofu** [comment]
Ok let's take a simple example:
- Our snap creates a TFHE private key for each account (= wallet addres).
- Each account (`m/44’/60’/0’/0`, `m/44’/60’/0’/1`, ...) but also all imported accounts need a dedicated TFHE private key. It means that the seed is different for each account (derived or not)

So now imagine a snap method which do allow a website to decrypt with the TFHE key.
- First, when the website will call our snap, we have no idea the query is for Account1, Account2, or an imported account. We need to trust the website on that. In the snap, it would be useful to have some context.
- Second, if the account used on the website is an imported account, we can't get any deterministic entropy for this wallet.

**Comment by immortal-tofu** [comment]
> It is not possible to tell which address is the currently selected address. I think the best approach would be prompt the user with a dialog of type "prompt" to input their public key and then derive an address based on that.

Today, we ask the website to send  the wallet address as parameter and we use it with 12-words entropy. It works, but it doesn't work for imported accounts obviously (it's not deterministic).

**Comment by immortal-tofu** [comment]
To be clearer, the newly added `snap_getEntropy` could have one more parameter to generate entropy based on selected account.

- `Object`
  - `version` - The literal number 1. This is reserved for future use.
  - `salt` - An arbitrary string to be used as a salt for the entropy. This can be used to generate different entropy for different purposes.
  - `account` - A boolean to get entropy relative to current selected address instead of relative to user account (12 words).

**Comment by kenhkan** [comment]
Closing this as we will not be able to address this.
