### ISSUE TITLE
Figure out a way to include the snaps webpage in our documentation

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1222]

**Comment by ziad-saab** [comment]
@Montoya what was the goal of this ticket? Was it to move the content from https://metamask.io/snaps/ in the docs? Or to have a link to that page from the docs?

**Comment by Montoya** [comment]
@ziad-saab To have a link to that page in the docs.

**Comment by Montoya** [comment]
For context, this section: https://docs.metamask.io/snaps/get-started/install-snaps/#install-metamask-flask
links to the Flask webpage in a non-intrusive way. 

The solution to this ticket may be to just update this first section: https://docs.metamask.io/snaps/ into: 

[Snaps](https://metamask.io/snaps/) is an open source system...

**Comment by Montoya** [comment]
I no longer think this is necessary, so closing the issue!
