### ISSUE TITLE
Sometimes `wallet_requestSnaps` fails silently

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/snaps#1233]
I am seeing that `wallet_requestSnaps` sometimes fails silently with no logs in the browser extension at all and no errors on the dapp side.

Using `Flask 10.25` and `Chrome Version 110.0.5481.100`.

The calling code looks like this:

```javascript
    console.log("Connect to snap", snapId);

    try {
      await ethereum.request({
        method: "wallet_requestSnaps",
        params: { [snapId]: {} },
      });

      if (typeof redirect === "string") {
        navigate(redirect);
      } else {
        redirect();
      }
    } catch (e) {
      dispatch(
        setSnackbar({
          message: `Could not connect: ${e.message || ""}`,
          severity: "error",
        })
      );
    }
  }
```

I am logged in to Flask, the snap is already installed but when I go to settings the snap is marked as stopped.

I can workaround this by refreshing the page and then it tends to connect but obviously this creates a very poor UX.

It may be related to the snap being stopped? Any ideas?

**Comment by FrederikBolding** [comment]
Do you have a reliable way of reproducing this? I can't see an obvious reason why this would happen, as with an already installed snap we just return the snap data directly to the dapp 🤔

**Comment by tmpfs** [comment]
Indeed @FrederikBolding, the log statements shows I hit the code block, the catch never fires and the page does not navigate so I think it it safe to say the promise never resolves.

It is intermittent so there are no steps to reproduce. There are no runtime errors in the browser and the browser extension logs do not show *anything* when this occurs.

I wonder if it is something to do with how Chrome is managing access to the extension but have no idea. 

I am able to reproduce it [here](https://tss.ac)...after connecting I removed the `/#keys` part of the URL to go back to the main view at `https://tss.ac` and try again and it happened.

I made a short video to illustrate.

https://user-images.githubusercontent.com/238069/221070210-da4b22ff-4223-47bb-abbe-5f2b4ba83ac6.mov

**Comment by FrederikBolding** [comment]
Hmm, I wonder if this is a MetaMask communication issue and not a snaps-specific issue. I wasn't able to reproduce even on your website locally. Next time it happens could you try a handful of RPC methods just to see if you get a response to any of them?

Also, that extension background console is eerily quiet, did you reset it before recording? Otherwise, it would seem that the extension might not even be running

**Comment by tmpfs** [comment]
> Hmm, I wonder if this is a MetaMask communication issue and not a snaps-specific issue. I wasn't able to reproduce even on your website locally. Next time it happens could you try a handful of RPC methods just to see if you get a response to any of them?
> 
> Also, that extension background console is eerily quiet, did you reset it before recording? Otherwise, it would seem that the extension might not even be running

Yes @FrederikBolding i cleared the console beforehand. Ok, will see if i can find out more.

**Comment by panieldark** [comment]
Fwiw, I've repro'd this occasionally. Every ~1/6 times, a call to `wallet_requestSnaps` will hang, as though it was never invoked. Problematic UX issue, as they have to refresh and try again

**Comment by FrederikBolding** [comment]
This may have been related to an issue with the MetaMask that should be solved in the latest release. If this issue pops up again, please create another issue!
