### ISSUE TITLE
Separate `snap_manageState` into separate functions `snap_getState`, `snap_setState`, and `snap_clearState`

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps#1287]
The `snap_manageState` API is a bit strange currently, because you have to specify an `operation` for each request. It's better if the method was separated into three separate methods:

- `snap_getState`, similar to the `get` operation.
   ```ts
   await snap.request({ method: 'snap_getState', params: { key: 'foo' } });
   ```
- `snap_setState`, similar to the `update` operation, where`params` is the new state.
   ```ts
   await snap.request({ method: 'snap_setState', params: { key: 'foo', value: 1 } });
   ```
- `snap_clearState`, similar to the `clear` operation.
   ```ts
   await snap.request({ method: 'snap_clearState' });
   ```

`snap_manageState` can be deprecated, and mapped internally to one of the methods above, depending on the `operation`.

Right now we only have one-to-one mappings for permissions to their respective JSON-RPC methods. In order to accomplish the above, while using a single permission, we need to have a way to map one-to-many, from a single storage permission to all the methods above.

**Comment by kenhkan** [comment]
From refinement: PermissionController work needed. Hassan to continue work next sprint.

**Comment by kenhkan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-monorepo/1287?planning-poker) with Zenhub @ritave @hmalik88 @FrederikBolding @Mrtenz @GuillaumeRx @david0xd

**Comment by Mrtenz** [comment]
Done in #2916.
