### ISSUE TITLE
installing 1inch fusion sdk makes the build fail

### ISSUE THREAD

**Issue by fabriziogianni7** [MetaMask/snaps#1393]
### Discussed in https://github.com/MetaMask/snaps-monorepo/discussions/1392

<div type='discussions-op-text'>

<sup>Originally posted by **fabriziogianni7** May  9, 2023</sup>
# Description
I'm trying to use 1inch fusion sdk into a snap. unfortunately I got the following stack trace when building:

```
[TypeError <Object <Object <[Object: null prototype] {}>>>: Cannot read properties of undefined (reading 'from')
➤ YN0000: [snap]:   at Object.sha3 (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:74149:30)
➤ YN0000: [snap]:   at ABICoder.encodeEventSignature (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:71994:22)
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:72276:40)
➤ YN0000: [snap]:   at Array.map (<anonymous>)
➤ YN0000: [snap]:   at Object.set [as jsonInterface] (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:72250:42)
➤ YN0000: [snap]:   at new Contract (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:72420:36)
➤ YN0000: [snap]:   at Object.79.../../abi/AggregationRouterV5.abi.json (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:3572:28)
➤ YN0000: [snap]:   at o (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:36:19)
➤ YN0000: [snap]:   at eval (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:38:20)
➤ YN0000: [snap]:   at Object.80../cancel-order.encoder (eval at <anonymous> (eval at makeEvaluate (test-snap/node_modules/ses/dist/ses.cjs:2065:27)), <anonymous>:3589:28)]
```

can you provide any help here? maybe I need to add some additional configuration?

thaaaankssss</div>

source code: https://github.com/fabriziogianni7/test-snap

**Comment by Montoya** [comment]
It's highly likely that the 1inch fusion SDK is not compatible with SES. If it uses eval, it will not work. You can read more here: https://docs.metamask.io/snaps/how-to/troubleshoot/#fix-build-and-evaluation-issues

p.s. I cannot see the source code, likely the repo is private.

**Comment by FrederikBolding** [comment]
@fabriziogianni7 Hey there!

It looks to me like your snap is trying to use `Buffer` but doesn't have it available. You can polyfill Buffer by using the following example snap configuration: https://github.com/MetaMask/template-snap-monorepo/blob/8b591091fbce6d44baa6b5112c71d5c5f27841f8/packages/snap/snap.config.js
