### ISSUE TITLE
Move away from nanoid

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps#1403]
React Native is incompatible with `nanoid`, we should replace it for something different that is universal, uuid4 works, but also our own custom id generator is also good enough.

See related patch - https://github.com/MetaMask/metamask-mobile/blob/flask/patches/@metamask+snaps-controllers+0.26.2.patch

**Comment by FrederikBolding** [comment]
Turns out this may not actually be a problem. PLEASE HOLD OFF ON WORKING ON THIS ISSUE.

**Comment by FrederikBolding** [comment]
Closing as we don't need to do anything here.
