### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#1416]

**Comment by eriknson** [comment]
Since we’re using MetaMask's DS colors for the simulator as well, it should just be the dark version of the same system. 

Drafted up how it'd look like: https://www.figma.com/file/PKGiCZgVJ87pb0E6CwWXGN/Snaps-Simulator?type=design&node-id=260%3A10227&t=Nlv56wU7iuDYK4z5-1

**Comment by kenhkan** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps/1416?planning-poker) with Zenhub @FrederikBolding @ritave @Mrtenz @david0xd @GuillaumeRx @hmalik88
