### ISSUE TITLE
Snaps: Name Resolvers in Flask

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1425]

**Comment by kenhkan** [comment]
From sprint planning (yesterday): SIP has been merged. Pending agreement at next design sync.

**Comment by kenhkan** [comment]
From [refinement session on 2023-08-24](https://docs.google.com/document/d/1-JmduAtcwKvNUCvOX0FgZVi__gB-OVQuqhGB8t0MG0k/edit#bookmark=kix.pbn76htij7mg): How does ENS and petname fit in with the Snaps system?

**Comment by kenhkan** [comment]
From refinement:
* Implementation status: ready, to be merged
* Design for send flow TBD with Erik
