### ISSUE TITLE
Snaps localization

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1440]
Currently we do not support localization for snaps. There is no way for snaps to tell what language the MetaMask extension is using or to submit localized strings to the UI. This epic is for coming up with a full approach to i18n that supports all of the snaps use cases and makes it as easy as possible for developers to use multiple languages in their snaps.

**Comment by kenhkan** [comment]
From [initiative prioritization](https://www.figma.com/file/nAD7Pb55eLgZA2IG0BkSUB/2023-07-06-Initiative-prioritization?type=whiteboard&node-id=1-108&t=NmWKDdSVYB0H29fX-0):
- This is the “getLocale()” API and allowing localized strings in the manifest
- Can we do this iteratively or do we need both at once?
- Do we want to build an i18n framework for runtime?
