### ISSUE TITLE
[Proposal] move SLIP44/SNAPS_DERIVATION_PATHS paths into metamask utils

### ISSUE THREAD

**Issue by owencraston** [MetaMask/snaps#1467]
Currently we are deriving the coin/protocol names on both extension and mobile with the exact same code. This is something that could be moved into the utils so that both platforms could consume it. This also means updating these dictionaries can be done once. 

I suggest that we migrate the following methods...

- [coinTypeToProtocolName](https://github.com/MetaMask/metamask-extension/blob/49f8052b157374370ac71373708933c6e639944e/ui/helpers/utils/util.js#L524)
- [getSnapDerivationPathName](https://github.com/MetaMask/metamask-extension/blob/49f8052b157374370ac71373708933c6e639944e/ui/helpers/utils/util.js#L548)
- [SNAPS_DERIVATION_PATHS](https://github.com/MetaMask/metamask-extension/blob/49f8052b157374370ac71373708933c6e639944e/shared/constants/snaps.ts#L52)

These methods were duplicated on mobile in [this PR](https://github.com/MetaMask/metamask-mobile/pull/6443)

@FrederikBolding do you have thoughts on this?

**Comment by FrederikBolding** [comment]
We can and should move `coinTypeToProtocolName` to `snaps-utils` imo. 

The others are more difficult, they are essentially hardcoded values for the derivation paths supported by the snaps that'll launch with v1. We decided to put them in the client to have them easily updatable, but long-term we need a better solution that doesn't rely on us hardcoding the derivation path names.
