### ISSUE TITLE
Snap_notify should add badge text to the toolbar

### ISSUE THREAD

**Issue by mindofmar** [MetaMask/snaps#1485]
Suggestion: Improve `snap_notify` behavior to be more apparent to users by showing the notification badge on the toolbar.

On the left is `snap_dialog` which already includes this functionality. On the right is `snap_notify` which feels like it could be significantly improved by adding this. The current implementation relies on the user opening the popup UI of their wallet in order for them to realize a notification exists, which makes time-sensitive notifications like ours less effective. 

<img width="900" alt="image" src="https://github.com/MetaMask/snaps/assets/72634565/1acc17a2-11f4-424e-ae19-bf696bf9f6f8">

**Comment by cryptoKevinL** [comment]
Why not use the Alert Dialog instead?  I think this does exactly what you are looking for?

<img width="364" alt="Screenshot 2023-06-09 at 8 53 21 AM" src="https://github.com/MetaMask/snaps/assets/19207330/a8337766-a67e-4d77-9f8b-e4c662c07739">

I'm just using the example snaps at: https://metamask.github.io/test-snaps/5.3.0/ for reference.

**Comment by mindofmar** [comment]
@cryptoKevinL the latter functionality is what we're looking for. We tried the Alert Dialog, but it doesn't fit our use-case as well as inApp notifications would. Just feels like this is the missing piece to make inApp notifications perfect :)

**Comment by Montoya** [comment]
Following up on this, we cannot reliably show a badge for notifications from Snaps. If a Snap has a critical notification, it should use type `native` as well as `inApp` to help ensure the user will see it. https://docs.metamask.io/snaps/reference/rpc-api/#snap_notify
