### ISSUE TITLE
Request timed out. Job "x" failed to terminate gracefully.

### ISSUE THREAD

**Issue by orkunkilic** [MetaMask/snaps#1493]
Hi! I was able to run my snap a month ago, around 30 April last. However when I try to use it right now, I cannot get my snap installed to Flask.

After giving permissions, it loads around a minute then logs errors on console and returns Request timed out.

I am sharing the screenshot of errors.
![Screenshot 2023-06-11 at 14 21 15](https://github.com/MetaMask/snaps/assets/29154729/6966da65-ae8e-44d8-8ff5-2d8894c57c1e)

This is the snap I was trying to build: https://github.com/orkunkilic/rpch/tree/patch

**Comment by FrederikBolding** [comment]
@orkunkilic @mindofmar This may be a DNS issue that has been popping up at times. We are aware of this problem and working on it. Can you provide us with the network tab from the extension background console?
