### ISSUE TITLE
Manifest file should be localizable

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1508]
Strings in manifest file should be localizable

Research whether this can be done with the current manifest version 0.1 or if it requires breaking changes and should be done in 0.2 (if it makes for a better API, we can bump the version)

**Comment by FrederikBolding** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps/1508?planning-poker) with Zenhub @Mrtenz @david0xd @GuillaumeRx @hmalik88

**Comment by kenhkan** [comment]
From standup: E2E test update and doc needed
