### ISSUE TITLE
wallet_getLocale() SIP

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1509]
Create a SIP for feedback including: 

- Permission for getting locale of user
- Proposed implementation of this API method

**Comment by FrederikBolding** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps/1509?planning-poker) with Zenhub @david0xd @GuillaumeRx @hmalik88 @Mrtenz

**Comment by kenhkan** [comment]
From refinement: To investigate why the [old PR](https://github.com/MetaMask/metamask-extension/pull/14443) died first.

**Comment by kenhkan** [comment]
In Slack, Mirko G said on the [old PR](https://github.com/MetaMask/metamask-extension/pull/14443):

> this was put on the side when I developed on it as we did not have an agreement on how to implement these kind of changes (i.e. should it live inside flask first? should it be an experimental feature?). Functionality wise shoul be g2g

So remaining work is to rebase and decide how to bring it to production.

Mirko also mentioned [this unrelated PR](https://github.com/MetaMask/metamask-extension/pull/14548) that could be valuable from a user perspective.

**Comment by Montoya** [comment]
Back then there was no process for this, now we can ship to Flask and worry about how to ship to stable later.

**Comment by kenhkan** [comment]
From DM with Frederik:
1. Check with Snaps team to see if there is any issue with SIP-10: https://github.com/MetaMask/SIPs/pull/98
2. Check with DevEx team
3. Update and merge Frederik's PR: https://github.com/MetaMask/snaps/pull/1557
