### ISSUE TITLE
Get feedback on the name resolver API

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1510]
Get feedback from Mark & extension team on: 
    1. how name resolving should work in the future
    2. if our implementation is sufficient for v1
    3. what will be needed to support ENS in the future within our API
   
Possible outcome of this task is a SIP or a RAPID depending on how many internal stakeholders are needed to approve - please check with me if this starts to feel like a RAPID task

**Comment by Montoya** [comment]
Mark Stacey (shared libraries team) gave positive feedback and provided some design suggestions. Also was concerned about the security aspect of domain resolution and we assured that it would be an elevated permission on install. 

Ken to set up meeting with UX teams for extension UX, mobile, and confirmations UX. Nilsson to work on design examples. 

Should also make another task to research how this and our registry approach will be affected by multichain progress. 

Christian to explore possibility of engaging ENS community to develop ENS snap in the future.

**Comment by eriknson** [comment]
The petnames effort (starting in Q3) will benefit from an API / permission for a snap to suggest resolved names for an arbitrary (contract) address.

E.g. if a user is triggered a request from `0xEqT...83x`, the snap(s) will be able to suggest resolved name(s) to represent this entity by going forward, e.g. `mirror.eth`, `mirror.lens`, `mirror.web3`, etc.

![name-resolving.png](https://images.zenhubusercontent.com/6267f04f11d2b941f83b53a0/a0c64c78-617f-4c1e-b976-5ae767bf1e04)

**Comment by hmalik88** [comment]
@eriknson we don't need a permission for that, that's just another part of the UI that could hook into `onNameLookup`
