### ISSUE TITLE
Unblock `personal_sign`

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#1551]
We want to unblock `personal_sign` to give snaps a way to let users sign in, e.g. with SIWE.

This is blocked by figuring out how to show the snap origin properly on the `personal_sign` and SIWE screens.

**Comment by eriknson** [comment]
Intermediary design reviewed & ready: https://www.figma.com/file/7JOVfBCxfHiz8xOwbuWF3j/Snaps-Platform-v2?type=design&node-id=143%3A33053&mode=design&t=eHrJaRWUmi1XFrIT-1
