### ISSUE TITLE
Add new UI element to display secrets

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps#1552]
From a suggestion on Slack:

> Devs for 3rd party chain integration sometimes need to display private keys/credentials within mm-snaps dialogues but there is no safe component to do so. Currently, an extension has to ask the user for approval to show the private key and then render a 2nd dialogue to display it. However, there is no guaranteed time between approval click and displaying the key. The key owner may klick “show private key” and confirm that it should be shown in the dialogue but MM may take non constant time to display the 2nd dialogue up until a point in time where it is not safe anymore to display it on screen (bystanders).
>
> Recommendation: provide a snaps-ui/component credential() that renders a blinded html component with a show/hide and clipboard button. The user can unblind the key immediately (same dialogue) when it is safe to do so.

**Comment by kenhkan** [comment]
Pending research on other UI additions as well

**Comment by eriknson** [comment]
Drafted up some designs: https://www.figma.com/file/7JOVfBCxfHiz8xOwbuWF3j/Snaps-Platform-v2?type=design&node-id=121%3A29938&t=9oS7ibsR9YiSPUDV-1

![sensitive-content-component.png](https://images.zenhubusercontent.com/6267f04f11d2b941f83b53a0/b766b990-5b97-45aa-8a46-c13c32fcede7)

**Comment by Montoya** [comment]
That looks good but we should talk to Rachel about whether to align this with how other secrets are displayed in MetaMask

**Comment by eriknson** [comment]
Solved via [#1262](https://app.zenhub.com/workspaces/snaps-615b3a7c08d2b20015eb6c4e/issues/gh/metamask/metamask-planning/1262)
