### ISSUE TITLE
Add new UI element for markdown rendering

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps#1553]
From a suggestion on Slack:

> Devs seem to be unaware that @snaps-ui::text() renders markdown. Problem: can lead to CtrlChar/Markdown injection (no urls, mainly style) --> text shown to user may not be accurate.
>
> Recommendation: rename text() to markdown() and provide a pure unrendered text() ui component for snap dialogs.

Alternatively, rather than rendering markdown, we may want to look into something like:

```ts
text(`Foo ${italic('bar') ${bold('baz')}`);
```

To render: "Foo _bar_ **baz**".

**Comment by kenhkan** [comment]
Pending research on solution plan

**Comment by FrederikBolding** [comment]
Since we are doing JSX Markdown is no longer a priority.
