### ISSUE TITLE
Repo URL in snaps-simulator website points to old repo 

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1609]
The following link points to the old repository:

![Screenshot 2023-07-14 at 9.02.48 AM.png](https://images.zenhubusercontent.com/61fad535000896169845fff9/abb25f24-5b11-49fd-98e6-59c8069eb544)

**Comment by FrederikBolding** [comment]
@Montoya Do we just want it to point to https://github.com/MetaMask/snaps?
