### ISSUE TITLE
Support lifecycle hooks in Snaps Simulator and testing framework

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps#1647]

**Comment by kenhkan** [comment]
From refinement: Need design from ErikN before pointing

**Comment by kenhkan** [comment]
From refinement:
* Erik to design a page

**Comment by eriknson** [comment]
Need to sync this one with @Mrtenz

**Comment by kenhkan** [comment]
From sprint planning:
* We have other latest features that have not gone into simulator. e.g. custom UI, signature insights, etc
* Team needs a meeting to decide on what we need to update in simulator and/or testing framework
