### ISSUE TITLE
Corrupt snap installation depending on internet provider DNS

### ISSUE THREAD

**Issue by zwilling** [MetaMask/snaps#1649]
Dear MetaMask team,

There seems to be an issue when installing snaps with some internet providers.

After confirming the installation and permissions, the three dots animation window for installing the snap is shown forever and does not complete (waited >20min). There is no visible error and the "Installation complete" window is not shown.
When closing the stuck installation window and reloading the page, it looks like the snap has been installed. The website sees the snap in `wallet_getSnaps` and the Metamask settings lists the snap.
But when trying to use it a `MetaMask - RPC Error: Assertion failed.` error is returned.

The funny thing is that everything works perfectly fine after removing the snap and reinstalling it though another internet provider, for example mobile hotspot or a VPN. First I thought that this is just an issue unique to a particular internet connection, but we recently got feedback that a community member from Korea has the same issue. Using a VPN also resolved it for him/her, but it took a lot of guesswork to find that solution.

The issue happens not only with the Snap for Galactica ([link](https://app-devnet-v1.galactica.com/) if you want to try it out). I could also reproduce it with the Dialog Snap example on https://metamask.github.io/test-snaps/latest/ (see screenshots).
However the Test-Snap front-end seems to detect the timeout properly. So to get the `Assertion failed.` error there, I had to restart the browser during the installation.

I tired to dig up more information about the issue by inspecting the extension with the DevTools on Chrome. It seems to be caused by a DNS resolution error of  `execution.metamask.io`.
![install-stuck](https://github.com/MetaMask/snaps/assets/1598646/d7cad54b-24eb-414a-a2f9-9d1c08fb8f7c)
![assert-failed](https://github.com/MetaMask/snaps/assets/1598646/f8fb6838-3354-4a89-9377-4b003c40805b)

The `dig` command line tool also fails to resolve `execution.metamask.io` with the bad internet provider DNS:
![dig-fail](https://github.com/MetaMask/snaps/assets/1598646/b10d38ba-7f6a-4143-9ec4-bbdd3ec772be)
It works when resolving `docs.metamask.io` instead
![dig-other-url](https://github.com/MetaMask/snaps/assets/1598646/b0dab13c-fb69-4c5e-b267-5db4eb3f3f0e)
and after turning on the VPN:
![dig-vpn](https://github.com/MetaMask/snaps/assets/1598646/08667637-3f94-4882-85ea-02af45cb9585)

Can you do anything to solve this DNS resolution problem?
Or detect this problem during snap installation to inform the user on how to work around it?

**Comment by Mrtenz** [comment]
Thanks for the report! This is (unfortunately) a known issue. We're working hard on getting this resolved with our DNS provider!

**Comment by FrederikBolding** [comment]
Thanks for reporting. This should be resolved in the latest version of Flask and stable. Please open an issue if you see this problem again!
