### ISSUE TITLE
feature_request: increase STORAGE_SIZE_LIMIT

### ISSUE THREAD

**Issue by martines3000** [MetaMask/snaps#1664]
Increase the [STORAGE_SIZE_LIMIT](https://github.com/MetaMask/snaps/blob/9037d2f53fadcc944b6ca662917779d5a52314b2/packages/rpc-methods/src/restricted/manageState.ts#L140) to 200MB (209715200 bytes).

This would allow snaps that require larger datasets to load them on the first startup (fetch from remote server) and store them locally. This dramatically reduces the snaps bundle size and improves the cold start (wake up) times.

We are experiencing this issue because we are using Polygon ID circuits (the size is approximately 127 Mb).

This would resolve our problem.

**Comment by martines3000** [comment]
@FrederikBolding Any updates/information on this ?

**Comment by FrederikBolding** [comment]
@martines3000 Sorry for the radio silence, we are still discussing internally. I'll try to get an update for you soon!

**Comment by martines3000** [comment]
@FrederikBolding Any new updates/information on this ?

**Comment by FrederikBolding** [comment]
@martines3000 Sorry for the lack of response, we aren't sure yet whether we can increase the storage limit much more. It also feels like a slightly hacky solution. Would an API like the one I suggested in https://github.com/MetaMask/snaps/issues/1778 be useful to your use-case? I'm wondering if you could bundle the auxiliary files needed for the snaps and lazy load them as needed?
