### ISSUE TITLE
Correct documentation for proposedName

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#1676]
https://github.com/MetaMask/snaps/tree/main/packages/snaps-cli#the-snap-manifest
https://github.com/MetaMask/specifications/blob/main/snaps/publishing.md#snap-manifests

These examples don't have a human readable name as `proposedName`, this should be corrected.

**Comment by Montoya** [comment]
Fixed here: https://github.com/MetaMask/specifications/pull/13

And here: https://github.com/MetaMask/snaps/pull/1722
