### ISSUE TITLE
cors problem with snaps quickstart

### ISSUE THREAD

**Issue by seddik11** [MetaMask/snaps#1714]
Hi,

I was following this [tutorial](https://docs.metamask.io/snaps/get-started/quickstart/) to start my first snap however I encountered this cors error when i try to connect.

BTW I am using github codespace.

Thank you

![image](https://github.com/MetaMask/snaps/assets/17779368/801950d7-7cd7-4e69-a59b-ed9a376c047e)

**Comment by seddik11** [comment]
Hi thank you for your reply.

I didn't change anything in the code. I just used this command `yarn create @metamask/snap your-snap-name` to create the app. Except this line I changed from localhost to the domain where the app is runnning

![image](https://github.com/MetaMask/snaps/assets/17779368/985c94ce-4f4a-4121-b3d5-eeeabd1a55d7)

because of this

![image](https://github.com/MetaMask/snaps/assets/17779368/3b59201e-3471-4e78-95ab-51f5a901081f)

**Comment by seddik11** [comment]
I got this error also when i try to connect

![image](https://github.com/MetaMask/snaps/assets/17779368/25810be3-bdbe-4219-aed1-20565bcbb69d)

**Comment by Montoya** [comment]
There may be an issue in the create-snaps package. What version of node are you running? If you can't get it to work, I recommend cloning this template and running that locally without changing anything: https://github.com/MetaMask/template-snap-monorepo

**Comment by seddik11** [comment]
Thank you for your help.

I was able to have the app running successfully on localhost except this error I see in logs (BTW I am on a linux environment on chromebook)

![image](https://github.com/MetaMask/snaps/assets/17779368/50cfd2be-6d30-4636-b7d0-800e96b85a54)

But when I try to connect I have two problems:

first one is this error message

![image](https://github.com/MetaMask/snaps/assets/17779368/75fa6ef0-18fa-4daa-831a-217448c70382)


second thing I can't scroll down to accept and go to next step

![image](https://github.com/MetaMask/snaps/assets/17779368/300e82f2-86ef-4c55-bd9e-7de3834834e7)

**Comment by seddik11** [comment]
I was able to run it successfully on windows locally

**Comment by kenhkan** [comment]
Closing this since GitHub Codespaces is not something that the snaps team currently supports.
