### ISSUE TITLE
modify transaction params onTransaction event

### ISSUE THREAD

**Issue by seddik11** [MetaMask/snaps#1721]
Hello,

I am interested to build a snap that will modify the transaction params (data etc..) when the onTransaction event is triggered. The UX is as follow:

The user will install the snap and give permissions
Dapps don't need to call a snap RPC or anything just when the user try to send the transaction and before confirmation the snap will make some modifications and ask user to confirm. Is it possible to do that  ?

I added "endowment:ethereum-provider" to the snaps manifest and tried to call "eth_sendTransaction" from the snap (within onTransaction function) but didn't work. 

Your help is much appreciated.

**Comment by seddik11** [comment]
Is it possible to call "eth_requestAccounts " and sign a raw transaction ?

![image](https://github.com/MetaMask/snaps/assets/17779368/31e42cc2-842b-442c-b9da-68b521611dab)

**Comment by Montoya** [comment]
This is not currently supported by our API. If you could describe what you are planning to do, we can consider it in our roadmap.

**Comment by seddik11** [comment]
Thank you for your answer.

I would like to build a snap that is simple for adoption both by the user and the dapp developer. the only thing needed is that the user will install the snap on his wallet. No RPC needed to be called or integrated by dapps. That's why I find onTransaction method is very userful.

I would like to have this experience: when the user clicks on some button on some dapp to send a transaction via metamask the snap would be able to propose a new transaction or make some modifications to the triggered transaction (with some message displayed like transaction insights) and it's always up to the user to confirm or not.

Thank you

**Comment by Montoya** [comment]
Thanks for that. That would require a transaction hook that is different from onTransaction. Will talk about with the team internally.
