### ISSUE TITLE
Raise default timeout for Snaps 

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1753]
The default timeout for Snaps requests is 1 minute. We should raise this to 2 minutes until we ship better support for background tasks. 

After this is changed in Snaps, a separate ticket for updating the extension integration should be created.

**Comment by FrederikBolding** [comment]
IMO this warrants more discussion, not ready for implementation.

**Comment by Montoya** [comment]
Currently it sounds like we should not do this. There are other solutions that could work instead.

**Comment by FrederikBolding** [comment]
Will close for now, we can open another issue if we decide to revisit this.
