### ISSUE TITLE
Consider a static file API

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#1778]
Seems that a general problem for larger snaps that require large WASM modules (or other large files) is that the cold start is slow. What if instead of using our state API for this (which is kind of hacky) we build an API that let's snaps lazy load it's own static files at runtime?

E.g.
```
export const onRpcRequest: OnRpcRequestHandler = async ({ origin, request }) => {
  const program = await snap.request({ method: 'snap_loadFile', params: { fileName: 'program.wasm' }})
  const module = await WebAssembly.compile(program);
  const wasm = await instantiate(module, {});
  (...)
};
```

A snap could then specify the static files it needs at runtime in the manifest.

**Comment by martines3000** [comment]
Hi. I have 2 questions:
1. Where would the snap load the files from. Would we just package the needed files together with the `snap.js` file and publish it on NPM?
2. Would this be extensible, as to be able to load other large files like JSON (`file.json`, etc...), or would this be limited to `.wasm` files?

Overall, I find the idea great :+1: , and it would definitely help projects with large files.

**Comment by FrederikBolding** [comment]
> 1. Where would the snap load the files from. Would we just package the needed files together with the `snap.js` file and publish it on NPM?
> 2. Would this be extensible, as to be able to load other large files like JSON (`file.json`, etc...), or would this be limited to `.wasm` files?


1. Yeah, I imagine they would just go in the dist folder next to the snap bundle. You would have to reference them in the manifest, e.g. `files: ["./dist/foo.json"]` and that should make them loadable asynchronously at snap runtime.
2. I don't see why this couldn't work for any file type, `loadFile()` could just return an `Uint8Array` and the snap parse that as it wants to.

**Comment by FrederikBolding** [comment]
@martines3000 Coming soon to Flask 👀
