### ISSUE TITLE
Simplify checkbox view of elevated opt-in at Snap installation

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#1807]
If a Snap requests lots of derivation paths, which is really one BIP32 or BIP44 with multiple caveats, they could be displayed as a paragraph with one checkbox rather than a list of checkboxes

**Comment by kenhkan** [comment]
From sprint planning: Erik to provide Figma and David to implement

**Comment by eriknson** [comment]
Design: https://www.figma.com/file/Wlwk0cTx6PQkNhiX7vN13e/Snaps-Platform-v1?type=design&node-id=869%3A19060&mode=design&t=O1LuXuP2dneJwOsJ-1

**Comment by Montoya** [comment]
This is pending copywriting review but is ready for implementation

**Comment by eriknson** [comment]
Copy reviewed and updated by @coreyjanssen so final design is good to go: https://www.figma.com/file/Wlwk0cTx6PQkNhiX7vN13e/Snaps-Platform-v1?type=design&node-id=914%3A10996&mode=design&t=hhyidvYvWYpyylkM-1
