### ISSUE TITLE
Implement `SnapError`

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps#1824]
If a Snap throws a `SnapError` (standardised error class), the Snap should not crash. This is useful in non-JSON-RPC contexts, such as `onTransaction`, `onCronjob`. The `SnapError` should be serialisable to JSON internally:

```ts
throw new SnapError(error);
// { code: -32000; message: error.message; data: { stack: error.stack }}

throw new SnapError('message'); -->
// { code: -32000; message: 'message'; }

throw new SnapError({ code: ...; message: ...; });
// { code: ...; message: ...; }
```

Related to #1779.

**Comment by kenhkan** [comment]
From sprint planning: Same solution as https://app.zenhub.com/workspaces/snaps-615b3a7c08d2b20015eb6c4e/issues/gh/metamask/snaps/1779. Setting SP = 0
