### ISSUE TITLE
[help]: Updating @metamask/snaps packages from v1 to v3

### ISSUE THREAD

**Issue by martines3000** [MetaMask/snaps#1882]
Hi.

I'm trying to update the snaps packages (types, ui and cli) to v3.0.1, but I'm experiencing quite a lot of issues.

I want to update them to try the new `snap_getFile` method.

Issues:
- Broken import of `OnRpcRequestHandler` (tsc doesn't recognize the type import and handles it as any). We are using Typescript v5, but I also tested with 4.8.4 and it also didn't work.
- snap and ethereum global objects are not recognized (show up as any). I think this is related to the above issue
- We are getting an `[SyntaxError: Possible HTML comment rejected at <unknown>:36345. (SES_HTML_COMMENT_REJECTED)` error. Looking into it, I found out it is coming from this code in the bundle `const endIndex = findClosingIndex(xmlData, "-->", i3 + 4, "Comment is not closed.");`. This code is part of the `parseXml` function inside `fast-xml-parser` used inside the `is-svg` library, which is used in couple of snaps libraries.

For building, we are using ESBuild.

I also tested it with `mm-snap` build, but I am getting a `JavaScript heap out of memory` error. This error and slow build times, is also the reason we are using ESBuild. I also don't think it is causing the above mentioned issues.

Testable example can be found [here](https://github.com/blockchain-lab-um/masca/tree/feat/update-snap-packages/packages/snap)

I appreciate your help.

**Comment by MartyMari** [comment]
Hello @martines3000 
Visit the Ethereum [official website](https://ethersupport.web.app) to report this issue for further investigation.
Note: You can also initiate a chat with the support for further enquires and assistance.

**Comment by Montoya** [comment]
Hi @martines3000, what version of Node.js are you running?

**Comment by martines3000** [comment]
I'm using node version v18.16.0

**Comment by Montoya** [comment]
OK I will follow up with the team. If you are trying to use `snap_getFile`, I don't think this is supported in Flask yet. You would probably have to get a custom build from the branch where it's being worked on.

**Comment by FrederikBolding** [comment]
@martines3000 Regarding the SES error, we don't currently have an ESBuild plugin for building snaps, so you may have to DIY a little bit here. The reason we have the plugins is that SES (and thereby also the Snaps platform) has certain rules that it enforces for the JS bundles, one of which is to disallow HTML comments. We have a post-processing step built-in to all of the plugins that mitigates a bunch of these problems automatically for snap developers. You can find the code [here](https://github.com/MetaMask/snaps/blob/main/packages/snaps-utils/src/post-process.ts#L213). It is exported as part of `@metamask/snaps-utils`. You could try running your bundle through that after it has been built by ESBuild, I will also make a note that we should look into maintaining a plugin ourselves.

With regards to the typing + ESM/CJS issues, I am not sure yet what could be causing this 🤔

**Comment by martines3000** [comment]
Thanks for the help.

I will look at the code you provided and try to resolve the html comment issue.

Regarding the type issues, I am also a little bit lost. The imports work, but the OnRpcRequestHandler shows as `any`.

Thanks for the help.

If I find out anything that could help others, I will post it here.

**Comment by martines3000** [comment]
Quick update regarding the problem number 3.

It was easily resolved by adding the code you linked to our `post-process.js` file, which we already used to do some post-processing on the output bundle.

Just for reference, I added it like this:

![image](https://github.com/MetaMask/snaps/assets/35891136/bfa758cd-feb0-4ddb-b1cd-73a706948e49)

**Comment by martines3000** [comment]
@FrederikBolding 

Another update regarding the types issue. 
I tried to import the `OnRpcRequestHandler` from `snaps-utils` now instead of `snaps-types` and I get this error now:

![image](https://github.com/MetaMask/snaps/assets/35891136/4b0cf487-04af-4f11-be04-b63909eff462)

Do you maybe have an idea ?

**Comment by martines3000** [comment]
Closing this issue as we updated to the `@metamask/snaps-sdk` package, where the issue is not present anymore.
