### ISSUE TITLE
Incompatible node version with module when running yarn create @metamask/snap

### ISSUE THREAD

**Issue by zikyfranky** [MetaMask/snaps#1900]
I can't seem to be able to create a snap, I think it has to do with the fact that dependencies need whole different versions of node.
I'm using nvm to switch between nodes, I have v20 LTS as my default, but when I run the create command, I get thrown this error

`@achrinza/node-ipc@9.2.2: The engine "node" is incompatible with this module. Expected version "8 || 10 || 12 || 14 || 16 || 17". Got "20.9.0"`

This seems like something with an easy fix like switching my node version, so I tried that, switching to v17, on running the command, I got this error

`error @metamask/snaps-utils@3.1.0: The engine "node" is incompatible with this module. Expected version "^18.16 || >=20". Got "17.7.1"`

How do I satisfy both packages as I can only select a specific node version at a time?

**Comment by zikyfranky** [comment]
Something I forgot to mention is that using `npm create` instead of `yarn create` runs as should.

**Comment by Montoya** [comment]
Hi @zikyfranky, I apologize that this is a bit tricky. I think the best version to use is 18.16 or greater. Is there a version of @achrinza/node-ipc that is compatible with Node 18?

**Comment by kenhkan** [comment]
Closing this since there is no actionable next step for the snaps team.

@zikyfranky Please re-open if the above doesn't help for you.

**Comment by zikyfranky** [comment]
@Montoya my bad about the late reply, must have somehow missed the notification, `@achrinza/node-ipc` is a dependency of snap, so I do not know what it supports or doesn't support

Hey @kenhkan, it's fine closing it, never knew there was a response on here.

Using npm worked, so, I just used that instead of yarn, I do not know exactly why that should be the case.
