### ISSUE TITLE
[bug]: issues with `snap_getFile` RPC method

### ISSUE THREAD

**Issue by martines3000** [MetaMask/snaps#1919]
`snap_getFile` RPC method is not working when trying to load large files inside Chromium-based browsers.

I tested the new `snap_getFile` RPC method to load our Circuits for Polygon ID and encountered some issues.

**Encountered issue:** 
 After approving installation of Masca Snap MetaMask is stuck in the loading screen and sometimes if I wait long enough it just crashes.

I  also checked the network tab and can confirm that it successfully loads (downloads) all the files.

---
Additional information:
- I used the `v11.5.0` branch of the MetaMask extension to build the flask version and test it.
- **Works** with `Firefox Browser Developer Edition` (tested on Linux and Windows). The initial installation is a little bit laggy, but after that, it works fine
- Doesn't work with Brave, Chrome and Chromium (all tested on Linux and Windows)
- I tested both with a local build and a build published to NPM
- Total Circuit size on NPM is 133MB
- It works on Chromium-based browsers if I try to load only 1 Circuit (around 35MB), albeit still a little bit laggy/slow.

Any ideas what would be causing the issues in Chromium-based browsers?

**Comment by FrederikBolding** [comment]
Hey @martines3000!

I will look into this more, I assume the NPM version you are referencing is `1.2.0-beta.0`, correct?

**Comment by martines3000** [comment]
Yes that is correct (version `1.2.0-beta.0`. Thank you! :+1:

**Comment by FrederikBolding** [comment]
Thank you for reporting this, I opened a PR to fix it here: https://github.com/MetaMask/metamask-extension/pull/21711

Can you verify that it fixes the slowness of the UI on your end too?

**Comment by martines3000** [comment]
@FrederikBolding 
Thanks for the quick fix

I tested it with your PR and it also works now in Chromium browsers.

The install time still takes quite some time, but it works now.

The download (on my internet) takes around 8 seconds, but the total loading (waiting time) before the `Install` button is available is around 1 minute. I'm not sure what would be causing this. I tried looking at the performance profiler in chrome, but nothing stands out. The actual work that is being done is quite fast (around 5s). Do you maybe have any additional ideas ?

Including a screenshot (probably not too helpful, but still :slightly_smiling_face:):
![image](https://github.com/MetaMask/snaps/assets/35891136/6861f946-880f-4972-8155-f45e82dc5a03)

**Comment by FrederikBolding** [comment]
@martines3000 The long install time is due to processing done after the snap has been fetched, for example, calculating the checksum. This is taking an enormous amount of time right now, especially for large snaps, due to a Chromium bug. We have filed this bug with the Chromium team and are awaiting it to be resolved.

**Comment by martines3000** [comment]
@FrederikBolding

One more question. The Chromium bug that you mentioned is only related to snaps that use the `snap_getFile` API, right ?

I'm asking this, because the install time and processing time for installing our snap when bundled in 1 ˙snap.js` files is really fast, compared to when using multiple files and loading them with `snap_getFile` API.

**Comment by FrederikBolding** [comment]
> @FrederikBolding
> 
> One more question. The Chromium bug that you mentioned is only related to snaps that use the `snap_getFile` API, right ?
> 
> I'm asking this, because the install time and processing time for installing our snap when bundled in 1 `snap.js` files is really fast, compared to when using multiple files and loading them with `snap_getFile` API.

The Chromium bug impacts `Uint8Array` directly and operations on those. We have been looking at your snap specifically as one that is impacted hard by this bug and installation seems to take quite long because of that. It is not directly related to the static file API.

In your "fast" example where are the static files located? In the bundle with everything else? If so, it could be that the performance characteristic is slightly less affected by the performance bug with 1 file compared to multiple. There is also a performance overhead in storing the static files compared to the single bundle.

**Comment by martines3000** [comment]
The fast example is our version `1.0.0`, where the large circuits are directly bundled into the final bundle as `base64` encoded values. The bundle size is large but the install step doesn't take much time (with download included around 20 to 30 seconds).

With static files its around 60 seconds total.

**Comment by FrederikBolding** [comment]
Yeah, some extra overhead is expected from the static file API. But we expect the runtime to be drastically reduced when the Chromium bug is fixed for both cases.

**Comment by FrederikBolding** [comment]
@martines3000 FYI, I found a way to reduce the runtime of the checksum drastically, will be released in the near future and should help both when using the file API and not! https://github.com/MetaMask/snaps/pull/1953
