### ISSUE TITLE
Limitations on the type of data returned by Keyring SubmitRequest

### ISSUE THREAD

**Issue by LaplaceMan** [MetaMask/snaps#1921]
I want to utilize Keyring's features first SCW to log in directly to the DApp and interact with it. When I get the signature of the Owner of the SCW (Smart Contract Wallet) in Snap, return it directly, but there is an error: ` expected the value to satisfy a union of 'object | object', but received. 0x2a4665cffcd9f9....`
Is there a solution for this?

this is my functon：
```shell
  async submitRequest(request: KeyringRequest): Promise<any> {
    if(request.request.method == EthMethod.PersonalSign) {
      await ethereum.request({
        "method": "eth_requestAccounts",
        "params": []
      });
      const sig = await ethereum.request({
        method: 'personal_sign',
        params: [
          `0x${Buffer.from((request.request.params as Array<string>)[0]?.toString(), 'utf8').toString('hex')}`,
          scwOwnerAddress
        ]
      })
      return sig
    }
}
```

**Comment by danroc** [comment]
Hey @LaplaceMan, the `submitRequest()` method should return a reponse like:

```ts
return { pending: false, result };
```

or

```ts
return { pending: true, redirect: { message, url } };
```

depending if it's implementing the [sync or async transaction flow](https://github.com/MetaMask/keyring-api/blob/main/docs/architecture.md#transaction-flows). You can also get some more details [here](https://github.com/MetaMask/keyring-api/blob/main/README.md#account-snaps).

**Comment by LaplaceMan** [comment]
> Hey @LaplaceMan, the `submitRequest()` method should return a reponse like:
> 
> ```ts
> return { pending: false, result };
> ```
> 
> or
> 
> ```ts
> return { pending: true, redirect: { message, url } };
> ```
> 
> depending if it's implementing the [sync or async transaction flow](https://github.com/MetaMask/keyring-api/blob/main/docs/architecture.md#transaction-flows). You can also get some more details [here](https://github.com/MetaMask/keyring-api/blob/main/README.md#account-snaps).
> 
> Thanks for opening this issue, we will improve the error messages in the future.

Thank you for your reply. One scenario I'm testing is logging into Opensea using the ERC-4337 account in Snap, it needs to get the signature of the ERC-4337 Owner, I'm trying to return this signature directly, but because of the type restriction it seems to only return objects? Or is there a more appropriate way to accomplish this scenario?

**Comment by LaplaceMan** [comment]
> Hey @LaplaceMan, the `submitRequest()` method should return a reponse like:
> 
> ```ts
> return { pending: false, result };
> ```
> 
> or
> 
> ```ts
> return { pending: true, redirect: { message, url } };
> ```
> 
> depending if it's implementing the [sync or async transaction flow](https://github.com/MetaMask/keyring-api/blob/main/docs/architecture.md#transaction-flows). You can also get some more details [here](https://github.com/MetaMask/keyring-api/blob/main/README.md#account-snaps).
> 
> Thanks for opening this issue, we will improve the error messages in the future.

@danroc Thank you for your reply. One scenario I'm testing is logging into Opensea using the ERC-4337 account in Snap, it needs to get the signature of the ERC-4337 Owner, I'm trying to return this signature directly, but because of the type restriction it seems to only return objects? Or is there a more appropriate way to accomplish this scenario?

**Comment by danroc** [comment]
Hi @LaplaceMan, two things:

- ERC-4337 accounts are not _fully_ supported yet. We are working on adding support for signing UserOperations.
- You can return an object as in the example above, MetaMask will return only the`result` to the caller (OpenSea in this case):

  ```mermaid
  sequenceDiagram
  autonumber

  participant Snap
  participant MetaMask
  participant OpenSea

  Snap ->> MetaMask: { pending: false, result };
  MetaMask ->> OpenSea: result
  ```

**Comment by danroc** [comment]
Hi @LaplaceMan, sorry for the delay, I missed your answer.

We are working to enable `eth_signTransaction` in the Snap's Ethereum provider, should be available soon, but I don't have an ETA.

**Comment by danroc** [comment]
I'm closing this issue since the original problem was solved.

Please feel free to create a new issue or reach out on our Discord server if you have other questions.
