### ISSUE TITLE
Firefox onRpcRequest unresponsive

### ISSUE THREAD

**Issue by panieldark** [MetaMask/snaps#1947]
Hey folks,

Our snap is unresponsive in both local and testnet snaps on Firefox browsers. Confirmed this with other team members, shared across Firefox (works as expected on Chrome).

Basically, onRpcRequest, nothing happens, and request times out.

https://www.loom.com/share/72f5806c256d4036b71539e446fc3c23

Any help would be appreciated.

**Comment by Montoya** [comment]
Can you point me to the source code for that RPC method?

**Comment by panieldark** [comment]
Hey Christian, sure thing

https://github.com/nocturne-xyz/snap/blob/main/src/index.ts#L115

**Comment by panieldark** [comment]
Looks like it's not reaching that point, as 
```
  console.log("Switching on method: ", request.method);
```
isn't firing. Also running this locally, looked like onRpcRequest wasn't being hit

**Comment by FrederikBolding** [comment]
@panieldark I cannot reproduce the unresponsiveness locally on Firefox using Flask v11.4.1.

It seems that the console logs from the snap aren't surfaced well in the Firefox environment, but that shouldn't cause unresponsiveness.

I think we are gonna need more details to reproduce.

**Comment by Montoya** [comment]
In order to reproduce the error locally I would need access to the test site repo...

**Comment by FrederikBolding** [comment]
Turns out this problem was passing `params: null` and the error handling was not throwing properly, this commit fixes that: https://github.com/MetaMask/snaps/commit/ddbc1b678d9cc06cacff8dd484b96c042121bc3e
