### ISSUE TITLE
Manifest shasum does not match computed shasum

### ISSUE THREAD

**Issue by Electr1Xx** [MetaMask/snaps#1960]
I tried to use static file API, but I ran into a problem. I can't install snap
<img width="592" alt="image" src="https://github.com/MetaMask/snaps/assets/10366688/144c7a9b-96c2-44f0-aa4a-3fcec7318690">
Here are all the changes I’ve made
https://github.com/rarimo/rarime/commit/2c37361b7a1d5260b79d8275b1c0f0c1f8d891b0
Metamask Flask I took from the branch `develop`. If I delete files from the manifest, everything works well
node v18.17.1 (npm v9.6.7)

**Comment by FrederikBolding** [comment]
Hmm, are you sure you are on the latest version of develop and that you have regenerated the shasum after build? 🤔

**Comment by FrederikBolding** [comment]
@Electr1Xx I just looked at your repo and it seems that you have a old version of  `snaps-utils` installed that is used for the checksumming. If you bump `snaps-jest` you can get rid of it and the checksum should be correct.

**Comment by lukachi** [comment]
Is this question still actual? I have same problem
<img width="1396" alt="image" src="https://github.com/MetaMask/snaps/assets/39623143/1a4e0791-c2ff-4d0c-a679-942ce1c0b42d">
<img width="402" alt="image" src="https://github.com/MetaMask/snaps/assets/39623143/20628271-8dc2-4405-bda9-40d25e98f89a">

**Comment by lukachi** [comment]
> @Electr1Xx I just looked at your repo and it seems that you have a old version of `snaps-utils` installed that is used for the checksumming. If you bump `snaps-jest` you can get rid of it and the checksum should be correct.

how the snaps-jest affect to shasum calculatings?

**Comment by FrederikBolding** [comment]
@lukachi This was a very specific problem related to  @Electr1Xx having very outdated packages installed, it doesn't look like it would be a problem on your end.

**Comment by lukachi** [comment]
sorry, but still encountering shasum error, might be something related to https://github.com/MetaMask/snaps/issues/1920

but in my manifest file everything seems okay 
<img width="710" alt="image" src="https://github.com/MetaMask/snaps/assets/39623143/1db620d4-bac8-4670-acb3-92be5f116e46">

**Comment by lukachi** [comment]
still encountering error

the error might be ocurred with something related to https://github.com/MetaMask/snaps/issues/1920

but i've only added files urls to manifest, and everything else wasn't changed and with previous snap cli worked properly
