### ISSUE TITLE
Request for Addition of Browser Memory Configuration in '@metamask/snaps-jest'

### ISSUE THREAD

**Issue by AMIRKHANEF** [MetaMask/snaps#2092]
I encountered an issue while writing a test for our snap, 

```
file:///H:/github%20desktop/something/node_modules/webdriverio/node_modules/puppeteer-core/lib/esm/puppeteer/common/Connection.js:134
            this._reject(callback, new TargetCloseError('Target closed'));
                                   ^
TargetCloseError: Protocol error (Runtime.callFunctionOn): Target closed
```

and after some investigation, it seems to be related to a potential memory limitation in the browser. I found that adding `"--disable-dev-shm-usage"` to the Puppeteer configuration could resolve the problem.

However, the challenge lies in implementing this configuration in the `@metamask/snaps-jest` environment. As a suggestion, it would be immensely helpful to have an option to configure browser memory settings within the `@metamask/snaps-jest` module. Something like:

```
module.exports = {
  preset: '@metamask/snaps-jest',
  testEnvironmentOptions: {
    browser: {
      headless: false,
      args: ['--disable-dev-shm-usage'],
    },
  },
};
```

Your consideration and assistance in resolving this matter would be highly appreciated.

**Comment by AMIRKHANEF** [comment]
@FrederikBolding.
Thanks for your response,
Great news! Looking forward to the new version.

**Comment by FrederikBolding** [comment]
@AMIRKHANEF The update was released, please go try it out and let us know what you think!

I will close this issue, but feel free to open up a new one with any problems!
