### ISSUE TITLE
Abstract system-level permissions

### ISSUE THREAD

**Issue by eriknson** [MetaMask/snaps#2235]
Some of our permissions might be too low-level for users to see during the installation phase.

Two things:
- Potentially introduce another weight (5) to group these implicit permissions
- Figure out where / how to show these in the UI (installation, settings, etc)

<img width="1111" alt="abstract-low-level-permissions" src="https://github.com/MetaMask/snaps/assets/34306844/1baea5d2-e758-4942-a4a5-0ddd87e91604">

**Comment by eriknson** [comment]
Me and @FrederikBolding are thinking something along these lines: https://www.figma.com/file/Wlwk0cTx6PQkNhiX7vN13e/Snaps-Platform?type=design&node-id=1648%3A21759&mode=design&t=J5R8zcPzxjEqEYTf-1

**Comment by eriknson** [comment]
No need to introduce another weight (5) for now. List of all permissions and their weights: https://www.notion.so/metamask-consensys/bac3299d2c5241c599d2e5e7986e72f7?v=ef742a61bd844435b7171bd2e90b447e

**Comment by eriknson** [comment]
Let's abstract permissions following these rules;
- **Installation:** if permission count > 3 we hide permissions with weight > 3
- **Update & Permission request:** Always show requested and revoked permissions, and approved permissions with weight <= 2

<img width="1111" alt="abstract-low-level-permissions" src="https://github.com/MetaMask/snaps/assets/34306844/b6e9db09-18bb-4aef-97b2-d6585f3343b7">

**Comment by david0xd** [comment]
Given that we always have single permission displayed on `Permission request` screen, integration of abstraction will be skipped. We will revisit this part when Dynamic Permissions are integrated. At the moment, there are not enough permissions to apply and test the approach on the `Permission request` screen/flow.
