### ISSUE TITLE
Custom UI positioning system

### ISSUE THREAD

**Issue by ziedbrini** [MetaMask/snaps#2278]

**Comment by eriknson** [comment]
We're leaning towards adding the options `direction="horizontal"` or `direction="vertical"` to the upcoming [Box component](https://github.com/MetaMask/SIPs/blob/706a1293c3dce13c759778ba13f7e6454ce7d821/SIPS/sip-23.md#box).

`<Box>` will have no margins or padding and an internal gap that is fixed at `8px`
