### ISSUE TITLE
Implement JSX

### ISSUE THREAD

**Issue by Mrtenz** [MetaMask/snaps#2289]
Following MetaMask/SIPs#133, we will start implementing JSX with a limited scope of the full proposal.

**Comment by ziedbrini** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps/2289?planning-poker) with Zenhub @Mrtenz
