### ISSUE TITLE
Support snap localization

### ISSUE THREAD

**Issue by Gudahtt** [MetaMask/snaps#232]
We should add support for snaps to be localized. We want it to be possible for any custom UI created by a snap to be localized with any locale supported by MetaMask.

Right now the only custom UI we have is the custom confirmation, but we should take into consideration that we will have much more custom UI in the future.

**Comment by Gudahtt** [comment]
Naively, to me the easiest way to support this would be to expose the locale to the snap and let them deal with it. But that would be tedious for snap devs.

A nicer API might be to accept a mapping of locale => string anytime we're accepting string input, and do the substitution ourselves.

**Comment by SebastienGllmt** [comment]
This is coming in https://github.com/MetaMask/snaps/issues/1509

**Comment by Montoya** [comment]
This will be solved by https://app.zenhub.com/workspaces/snaps-615b3a7c08d2b20015eb6c4e/issues/gh/metamask/snaps/1440
