### ISSUE TITLE
wallet_requestSnaps error 'Caveat "value" is invalid JSON.' in Firefox only

### ISSUE THREAD

**Issue by Janaka-Steph** [MetaMask/snaps#2320]
I just installed the snap template with `npx @metamask/create-snap my-snap`.

Running the demo app, `wallet_requestSnaps` fails on Firefox (but not on Chrome) with: 
```
MetaMask - RPC Error: Internal JSON-RPC error.
code: -32603
message: 'Caveat "value" is invalid JSON.'
```

**Comment by FrederikBolding** [comment]
Thanks for reporting this. I have opened a PR to the template repo to rectify this issue!
