### ISSUE TITLE
Support for Starknet mainnet

### ISSUE THREAD

**Issue by minhnguyennapaglobal** [MetaMask/snaps#2344]
When does Metamask wallet support Starknet mainnet as the list of popular network?
<img width="996" alt="CleanShot 2024-04-19 at 09 32 54@2x" src="https://github.com/MetaMask/snaps/assets/108506711/e3a5199c-a58e-4e30-9545-16152078666d">

**Comment by Montoya** [comment]
Hi @minhnguyennapaglobal , to add Starknet mainnet to MetaMask, install the Starknet Snap from our official directory here: https://snaps.metamask.io/snap/npm/consensys/starknet-snap/
