### ISSUE TITLE
Snap installation flow

### ISSUE THREAD

**Issue by plasmacorral** [MetaMask/snaps#2354]
After agreeing to connect a snap, the connected snap actually appears within Settings>Snaps before I have agreed to the installation.

Observed on Mac Sonoma 14.3.1 with Chrome 117.0.5938.92 in v11.14.1 (non-flask): [Recording](https://www.loom.com/share/3136a338c2ec4dc9bc5c2f23ca470721?sid=3e6488df-60be-4ae2-8bce-194b8a7e8b5a)

Expected result: Snap is not installed until user provides consent

Actual result: Can disable and remove the snap, prior to agreeing to install.

**Comment by Montoya** [comment]
Thank you for the report!
