### ISSUE TITLE
Snaps CLI should warn or error if “endowment:rpc” object is empty

### ISSUE THREAD

**Issue by Montoya** [MetaMask/snaps#2405]
If a Snap manifest has the RPC endowment with an empty object like so: 

`“endowment:rpc”: {}`

This will cause an error in MetaMask when attempting to connect like so: `An error happened: Invalid JSON-RPC origins: Must specify at least one JSON-RPC origin`

The CLI should warn that the endowment will not be functional without at least one origin such as `"dapps":true`

**Comment by FrederikBolding** [comment]
This happens because Superstruct `assign` doesn't copy over refinements, so when merging two structs [here](https://github.com/MetaMask/snaps/blob/main/packages/snaps-utils/src/manifest/validation.ts#L214) we lose some validation.
