### ISSUE TITLE
Deadlink

### ISSUE THREAD

**Issue by sulaimon23** [MetaMask/snaps#2474]
Npm publishers link leads to 404 page

<img width="1143" alt="Screenshot 2024-06-10 at 10 26 11 PM" src="https://github.com/MetaMask/snaps/assets/61692103/ff2ca428-607f-488a-a0d0-c12454ed2a52">

https://github.com/orgs/MetaMask/teams/npm-publishers

![Uploading Screenshot 2024-06-10 at 10.26.31 PM.png…]()

**Comment by FrederikBolding** [comment]
Hi! The team referenced here does exist, but it is not a public team, thus the link looks dead outside of the MM org.
