### ISSUE TITLE
`The Snaps execution environment failed to start` error appears after any RPC call in the most recent Chrome versions

### ISSUE THREAD

**Issue by ihordiachenko** [MetaMask/snaps#2518]
Hi, team! [RariMe snap](https://github.com/rarimo/rarime) has stopped working in the latest Google Chrome versions, with any RPC calls returning an error message `The Snaps execution environment failed to start`. The snap hadn't been changed for a few months before the issue was first reported, and it still works fine in Firefox. We couldn't locate any issues on our side. Could you take a look?

Steps to reproduce:
1. Install the latest Google Chrome version and MM
2. Go to https://robotornot.mainnet-beta.rarimo.com/
3. Install RariMe snap
4. Press **Create profile**
5. Get verified using **Civic** captcha
6. Get the verifiable credential
7. Hit "Generate Proof"
8. RPC call gets stuck indefinitely, no errors in the browser console or the network tab
9. Reload page
10. Any RPC call to snap or snap installation returns this error:
![photo1718899661](https://github.com/MetaMask/snaps/assets/11010444/48cc343b-544e-42ad-b7e6-5a1816aa98fd)

The issue is reproducible in:
Chrome Version 126.0.6478.61 (Official Build) (arm64)
MetaMask versions: 11.16.12, 11.16.10-flask.0

**Comment by seniorjoinu** [comment]
Having the same issue. Also began with recent chrome updates.

**Comment by ihordiachenko** [comment]
@seniorjoinu we've mitigated this issue by splitting all files over 65MB into smaller chunks and glueing them back in the runtime. Hope it helps you

**Comment by seniorjoinu** [comment]
@ihordiachenko 
> @seniorjoinu we've mitigated this issue by splitting all files over 65MB into smaller chunks and glueing them back in the runtime. Hope it helps you

Thanks for the advice! 
But it seems unrelated, since our

**Comment by Montoya** [comment]
@seniorjoinu which version of MetaMask or Flask are you on?

**Comment by seniorjoinu** [comment]
@Montoya 11.16.16 regular orange MetaMask

**Comment by FrederikBolding** [comment]
This was a symptom of the bundle size being too large, this will now result in an error following https://github.com/MetaMask/snaps/pull/2527
