### ISSUE TITLE
MetaMask Flask: RPC Error with wallet_requestSnaps Method in Snap Connection

### ISSUE THREAD

**Issue by Nick-1979** [MetaMask/snaps#2536]
I'm using the following code to connect to a published snap:

```
const connectSnap = async (origin: string): Promise<RequestSnapsResult> => {
  const { version } = SNAPS[origin];

  return await window.ethereum.request({
    method: 'wallet_requestSnaps',
    params: {
      [origin]: {
        version
      }
    }
  });
};
```

The code works fine on MetaMask, but it fails on Flask with the following error:
`inpage.js:1 MetaMask - RPC Error: Expected caveat to have a value property of a non-empty object of snap IDs.: At path: value.type -- Expected the value to satisfy a union of intersection | string, but received: "type". {code: -32602, message: 'Expected caveat to have a value property of a non-…of intersection | string, but received: "type".'}`

I would appreciate it if you could help me resolve this issue.

**Comment by FrederikBolding** [comment]
Hmm, it seems like you might have landed in a bad state somehow. Any idea how to reproduce this? What Snap ID are you trying to install?

**Comment by Nick-1979** [comment]
I was finally able to identify the root cause of the issue. The problem occurs when I have one version of the snap installed, either production or development, and then attempt to install other versions.
Given this understanding, I believe we can close the issue if you agree that it is not a serious problem
