### ISSUE TITLE
Research - understand how to integrate and how to proceed

### ISSUE THREAD

**Issue by ajeetd** [MetaMask/snaps#2558]
Develop plan.

**Comment by Montoya** [comment]
I am meeting with the Portfolio team this Friday to investigate. In the meantime, I have put together this doc: https://www.notion.so/metamask-consensys/Snaps-in-Portfolio-d0f96be02f704efaa50f8f2a2e1cf71c

**Comment by Montoya** [comment]
Portfolio team went with a simple solution, to link to Snaps Directory (opens a new tab). Sufficient for now. Will revisit a deeper integration when we have more capacity.
