### ISSUE TITLE
Issue with new JSX feature

### ISSUE THREAD

**Issue by pranavcpawar** [MetaMask/snaps#2603]
![image](https://github.com/user-attachments/assets/eb88c7c4-df72-4221-9ad2-c2b56df7cd3b)

I'm trying to use the new JSX implementation but encountered this error for home page. Can anyone help?

**Comment by FrederikBolding** [comment]
What version of the MetaMask extension are you seeing this on? Can you also provide a snippet of the UI you are trying to display?

**Comment by pranavcpawar** [comment]
I was using version 11
