### ISSUE TITLE
Restrictions on the length of the input line in a "promt" type dialog

### ISSUE THREAD

**Issue by kanntim** [MetaMask/snaps#2673]
How can I remove line length restrictions in the "promt" dialog? I insert a 500-character string into the input field, but only 300 characters are saved.
```
await snap.request({
    method: 'snap_dialog',
    params: {
      type: 'prompt',
      content: (
        <Box>
          <Heading>Save your Macaroon</Heading>
          <Text>Enter here your LN macaroon</Text>
        </Box>
      ),
      placeholder: '13ce5...',
    },
  })
```

**Comment by ziad-saab** [comment]
@kanntim can you please share a GitHub repo with your code?

**Comment by kanntim** [comment]
@ziad-saab here is the link: https://github.com/kanntim/lnd_snap
I'm just testing the create/snap template for now.

here is the path to the function of interest: /packages/snap/src/rpc/getLNDataFromSnap.tsx

**Comment by ziad-saab** [comment]
@kanntim thanks for sharing! It looks like you're trying to use the legacy dialog prompt, which indeed has a 300-character limit.

Instead you can use an interactive UI dialog (https://docs.metamask.io/snaps/features/custom-ui/interactive-ui/) with an `Input` component (https://docs.metamask.io/snaps/features/custom-ui/with-jsx/#input).

Here's a full example of using interactive UI: https://github.com/MetaMask/snaps/blob/main/packages/examples/packages/interactive-ui/src/index.tsx

Let me know if that takes care of your issue.

**Comment by kanntim** [comment]
@ziad-saab I had such a thought, but I didn't understand how to get data from the interactive UI input field? Could you tell me how to assign a value from the input field in the interactive ui to a variable?

**Comment by ziad-saab** [comment]
The code would look something like this. A difference with what you're doing now is that the logic would be split between displaying the form and receiving the value. You will receive the value in the `onUserInput` function

```tsx
import { UserInputEventType, type OnRpcRequestHandler, type OnUserInputHandler } from '@metamask/snaps-sdk';
import { Input, Button, Form, Field } from '@metamask/snaps-sdk/jsx';

export const onRpcRequest: OnRpcRequestHandler = async ({
  request,
}) => {
  if (request.method === 'hello') {

    const formId = await snap.request({
      method: "snap_createInterface",
      params: {
        ui: (
          <Form name="macaroonForm">
            <Field label="Macaroon">
              <Input placeholder="Macaroon" name="macaroon" />
            </Field>
            <Button type="submit">Save</Button>
          </Form>
        )
      },
    })

    await snap.request({
      method: 'snap_dialog',
      params: {
        type: 'alert',
        id: formId,
      },
    });
  }

  throw new Error('Method not found.');
};

export const onUserInput: OnUserInputHandler = async ({ event }) => {
  if (event.type === UserInputEventType.FormSubmitEvent && event.name === "macaroonForm") {
    console.log("macaroon", event.value.macaroon);
  }
};
```

**Comment by kanntim** [comment]
@ziad-saab  Thank you very much! You've helped me a lot!

**Comment by kanntim** [comment]
@ziad-saab Thank you very much! You've helped me a lot!
