### ISSUE TITLE
Latency when launching/closing the Snap UI

### ISSUE THREAD

**Issue by danroc** [MetaMask/snaps#2832]
There is some latency when launching and closing the Bitcoin Snap UI.

**Example:**

https://github.com/user-attachments/assets/768b427c-7975-49ce-b88f-256784136564

We suspect that **part** of the issue comes from reading or updating Snap's storage state. In our test, we observed that fetching an empty state took ~4 ms, while a state containing around 20 cached transactions took ~200 ms.

We can help with proper tests if needed.

**Comment by FrederikBolding** [comment]
We've made significant improvements to the speed of storing and retrieving state and shipped other improvements that reduces the need for using the state for interface purposes. Closing and we can create a new ticket if there are more perf issues to look into in the future.
