### ISSUE TITLE
Signature insights snaps and transaction insights snaps being blocked by "Experimental" improved signature/transaction feature.

### ISSUE THREAD

**Issue by hoshiyari420** [MetaMask/snaps#2839]
![image](https://github.com/user-attachments/assets/970e6c5f-9b32-4383-8092-ad30b08d7e0e)

Experimental feature which is ON by default blocks the signature insight snaps and transaction insights snaps. Is this expected behaviour?

Ideally, experimental features should support such "insights" related snaps since it does not modify their behaviour.

**Comment by FrederikBolding** [comment]
Insights are displayed on the redesigned signature screens in the `12.4.0` version of MetaMask, which is currently being rolled out!

**Comment by hoshiyari420** [comment]
Ah, maybe it's yet to be updated on Flask? I am using latest Metamask Flask version: 12.3.1-flask.0

**Comment by Montoya** [comment]
Yes that's the latest version on the store. If you want to get a newer version before it hits the stores, you can find a Flask build for Chrome here: https://github.com/MetaMask/metamask-extension/pull/27879#issuecomment-2416791263

But we will have 12.4.2 on the stores soon.
