### ISSUE TITLE
issue: issues with custom JSX UI types

### ISSUE THREAD

**Issue by martines3000** [MetaMask/snaps#2846]
Hi. We recently tried upgrading from the old UI to the new JSX UI, but we are having some issues.

I get the following error when trying to use the new components:
![image](https://github.com/user-attachments/assets/e90fd2e6-4cef-4f8f-921c-fef2670da575)

Link to source code: https://github.com/blockchain-lab-um/masca/blob/fc77fc3e85f2ec127900f9812bfe5911208df48a/packages/snap/src/UI.service.tsx#L50

Branch: `chore/upgrade-snap-jsx`

Any ideas what could be wrong here ?

This issues is happening with almost all component types.

Thank you for the help.

**Comment by Montoya** [comment]
Hi @martines3000 did you follow these steps when migrating your Snap code? https://docs.metamask.io/snaps/features/custom-ui/#upgrade-a-snap-to-use-jsx

**Comment by martines3000** [comment]
@Montoya Yes, we followed the mentioned guide.

1.  We use `@metamask/snaps-sdk": "6.9.0"`
2. We added `"jsx": "react-jsx", jsxImportSource": "@metamask/snaps-sdk"` to compiler options
3. We renamed the corresponding file from `.ts` to `.tsx`
4. We don't use eslint, so not changes were necessary there.

**Comment by FrederikBolding** [comment]
@martines3000 You likely need to add these dependencies too: https://github.com/MetaMask/snaps/discussions/2700#discussioncomment-10559294

**Comment by martines3000** [comment]
This solved our issue. Thank you 🙏 .

Sorry that I missed the discussion, I only looked in the "issues" tab 😓.

I will close this issue as it is resolved.

**Comment by FrederikBolding** [comment]
We'll make sure to document this better, you are definitely not the first person to reach out about this!
