### ISSUE TITLE
Consider letting Snaps expose settings that show up alongside the MetaMask settings

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#2874]
Consider letting Snaps expose settings that show up alongside the MetaMask settings.

Possibly let them expose an entire dynamic UI as a section in the settings view.

Consider how this experience differs between preinstalled and regular Snaps.

More details TBD.

- Preinstalled Snaps have own category
- Regular Snaps go in own settings page

**Comment by eriknson** [comment]
Should we scope this to be for pre-installed snaps only initially for the v1? And then introduce it to anyone as a v2

**Comment by Montoya** [comment]
Yes, scope for pre-installed only for v1

**Comment by eriknson** [comment]
Design: https://www.figma.com/design/uwco83tbwqt6rcZp9oa0YR/Custom-Settings-Section?node-id=1-63&t=MfWXXnWZk6CNngKC-1

**Comment by danroc** [comment]
We should consider adding the ability to mark a setting as privacy-related, allowing it to be included in the **Privacy** section of the settings.
