### ISSUE TITLE
Longer Running Processes Disrupted by `eth_getLogs`/`eth_getChainId` calls

### ISSUE THREAD

**Issue by radleylewis** [MetaMask/snaps#2885]
**Overview**

In our use case we are decrypting messages within the context of our MetaMask Snap. This process is quite time consuming (up to approx. 100 seconds). Our specific use case does not invoke calls to the network, however, the library used does invoke the `eth_getLogs` and `eth_getChainId` calls. In the case of their failure, the long running decryption process is interrupted. 

**Question**

Short of changing the library code making the calls, is there a way to suspend or prevent such calls (or protect a longer running process within the context of the snap from being disrupted)?

**Comment by FrederikBolding** [comment]
@radleylewis Are you referring to the Snap being terminated while waiting for decryption? Calling `eth_getLogs` or `eth_getChainId` should only get the Snap terminated if there are unhandled errors. Is it possible to simply catch these errors?

If not, then I think I need a better understanding of the problem 🤔

**Comment by radleylewis** [comment]
@FrederikBolding we were able to dig into the library causing issues and resolve the problem. Thanks for your help, I will close the issue.

**Comment by radleylewis** [comment]
@FrederikBolding we were able to dig into the library causing issues and resolve the problem. Thanks for your help, I will close the issue.
