### ISSUE TITLE
Support dapp origin identifier in methodImplementation context

### ISSUE THREAD

**Issue by tmpfs** [MetaMask/snaps#580]
Following on from the conversation in #548. 

If we take the `snap_manangeAccounts` feature that I am implementing for the *threshold signatures* snap as an example, I think it would be correct if the accounts it manages were not available to other dapps. Right now, this isn't possible as isolation is achieved using the `snapId` exposed via `context.origin`.

This permission is sensitive (like `getBIP44Entropy_*`) in that it allows access to private key information so in this instance it should be isolated to the owner dapp.

Would it be possible to expose the dapp `origin` on the `context` object so we could achieve this? As `origin` already is the `snapId` possibly we call it `originString` like the argument in the snap RPC handler for the moment? Although to prevent confusion, I think it would be good in the long run to rename `context.origin` to `context.snapId` and point `context.origin` to the dapp `origin` if possible.

/cc @rekmarks

**Comment by gantunesr** [comment]
This is no longer relevant since we do a verification using the `allowedOrigins` in the endowments
