### ISSUE TITLE
Allow snaps to talk to each other

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#606]
Snaps should be able to talk to each other. An example use-case would be a signer snap exposing it's signing RPC methods to other snaps.

We need to consider how we expose this functionality to snaps and how snaps ask for permission to talk to other snaps.

**Comment by rekmarks** [comment]
As it turns out, it is already possible for snaps to communicate with each other, ref: https://github.com/MetaMask/test-snaps/pull/61

The real challenge comes down to how we allow snaps to depend on each other.
