### ISSUE TITLE
Improve `@metamask/snaps-cli` unit tests

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps#74]
Following MetaMask/snaps-cli#74, there are still some unit test improvements to make:

- [x] Achieve 100% branch coverage for all files
- [ ] Test the built `evalWorker` file
- [ ] Test the `yargs`-generated `argv` object for all commands
  - See `TODO` in `cli.test.ts`

**Comment by rekmarks** [comment]
@hmalik88 how are we doing with this?

**Comment by hmalik88** [comment]
Haven't got to this issue yet, but it's partially blocked by #556 as that will change worker implementation possibly. We're at 100% coverage minus `eval-worker.js`, I need to have a chat with Kris from Agoric about testing lockdown (I had a method when working on execution-environments but I'm not sure if that's proper). Will be able to address after NFT NYC week.
