### ISSUE TITLE
Decide whether we want to support `rpc.discover` in the snap executor

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#889]
We currently support `rpc.discover` in the snap executor. We should decide whether that is a thing we want to keep doing. We do not use the OpenRPC file for anything else following https://github.com/MetaMask/snaps-monorepo/pull/844

**Comment by ritave** [comment]
I'm for removing it

**Comment by FrederikBolding** [comment]
We removed this in https://github.com/MetaMask/snaps/pull/1782
