### ISSUE TITLE
Solidify install experience

### ISSUE THREAD

**Issue by FrederikBolding** [MetaMask/snaps#892]
Ensure user feedback in the following cases for snap installations and updates:
- When a snap is being fetched
- When installation / updating succeeds
- When installation / updating fail

This should be done by creating a persistent popup during the install flow that shows feedback as the user is installing a snap as well as informs the user of the outcome of the install (success/fail). See @eriknson designs below.

This may require changes to the SnapController as well as the extension design.

Potentially as part of this the implementer could also combine the current two popups into one, this can also be done in another task if limiting the scope of this ticket is necessary. 

The goal of this ticket is to improve the install experience so that it is clear what is going on, especially when installing snaps with bad WiFi or similar.

### Outcome

We want to have to one pop-up for installation process.
We need to combine all installation for into 1 permission request.

### Work needed

1. Designs
2. Business logic
3. UI

**Comment by hmalik88** [comment]
oh I like this ^^ , let's talk about this during design sync

**Comment by hmalik88** [comment]
> Perhaps as part of this we could combine the multiple popups into one unified experience with loading spinners, error messages etc.

I like this, let's discuss in design sync!

**Comment by eriknson** [comment]
- Here are [current error state designs](https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=2044%3A38927) for connection, installation, and update.
- Here's a [success screen design](https://www.figma.com/file/kz987q7xsI9NzGvUZrc8LF/Snaps-UI?node-id=1611%3A30164) using our fox animation for when an installation / update succeeds.

Let's still discuss if it's possible to combine multiple popups in sequence into a unified experience including loading states etc.
