### ISSUE TITLE
MetaMask Snaps v1.0.0

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps#928]
Epic for MetaMask Snaps 1.0.0 tickets.

**Comment by kenhkan** [comment]
Closing this as we're using the release [MetaMask Snaps v1](https://app.zenhub.com/workspaces/snaps-615b3a7c08d2b20015eb6c4e/reports/release?release=Z2lkOi8vcmFwdG9yL1JlbGVhc2UvODU3MjM) to track all v1 launch items.
