### ISSUE TITLE
Consider creating API allowing custom domain / name resolutions for addresses.

### ISSUE THREAD

**Issue by ritave** [MetaMask/snaps#933]
Throughout hackathons, we were approached by multiple projects that wanted to have a snap with custom name resolution. For example to allow sending money to `@ritave` which would then resolve my Twitter account to my Ethereum address through some kind of service (eg ENS or their custom backend).

The ask is to allows snaps to be able to catch requests for address resolution in all places.

Example, but not limited to:
* JSON RPC commands
  * `eth_sendTransaction.to`
* Web Browser URLs
* Contact book
* MetaMask UI send dialog, both Ether and tokens 

Additionally, current domain resolution support inside main extension could be moved into a snap.

**Comment by Montoya** [comment]
This is being resolved by https://app.zenhub.com/workspaces/snaps-615b3a7c08d2b20015eb6c4e/issues/gh/metamask/snaps/1425
