### ISSUE TITLE
Remove endowment:long-running from Snap APIs

### ISSUE THREAD

**Issue by rekmarks** [MetaMask/snaps#945]
Each API available to snaps should be reviewed for consistency, cross-platform compatibility, maintainability, and usability ahead of our planned v1 release. This includes:
- All endowments, permissioned or otherwise
- All JSON-RPC methods, permissioned or otherwise, excluding those specific to the EIP-1193 provider and/or the Ethereum execution client interface

Known issues/open questions include:
- `endowment:long-running`
  - This endowment permits snaps to run forever. It's something of a hack/crutch, and we should consider very carefully whether to continue supporting it.

**Comment by rekmarks** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Snaps-Platform-615b3a7c08d2b20015eb6c4e/issues/MetaMask/snaps-monorepo/945?planning-poker) with Zenhub @Mrtenz @FrederikBolding @ritave @david0xd @GuillaumeRx @hmalik88

**Comment by kenhkan** [comment]
We need to come up with the list of features/aspects for v1 API. This should also be an epic that contains all the related features. We'll move this to the product backlog until we have that complete list.

**Comment by ritave** [comment]
Long running / background snaps are useful. Some of previous hackathon winners required that permission.

Examples uses:
1. Longer cryptographic calculations (for example RSA)
2. Polling for events from external servers
3. Polling for logs from blockchain and do automations based on that (for example automatic NFT bidding)

Though this permission is too broad, we need to figure out how to allow those usages to exist while removing this permission. 

---

A good starting point is how iOS [manages background tasks](https://developer.apple.com/documentation/backgroundtasks/choosing_background_strategies_for_your_app).
They're time limited, but allow for many use-cases.
1. Push messages
2. Cronjobs
3. URL downloads

Also see [Background Modes](https://developer.apple.com/documentation/bundleresources/information_property_list/uibackgroundmodes)

**Comment by GuillaumeRx** [comment]
`endowment:long-running` will be disabled in stable until we find a better/less *hacky* way to handle long running snaps.

**Comment by kenhkan** [comment]
From standup:
* Bringing this in and David will work on this. As a separate PR.
*
